# Generated by Django 4.2 on 2023-05-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Claim_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_numbers', models.CharField(max_length=100)),
                ('resolutions', models.CharField(max_length=100)),
            ],
        ),
    ]
